### ISSUE TITLE
Investigate moving to `uswds-gatsby` repo

### ISSUE THREAD

**Issue by davemcorwin** [18F/federalist-uswds-gatsby#10]

**Comment by brockfanning** [comment]
@davemcorwin I'd love to see this happen - is there anything I can do to help test/implement/etc?

**Comment by davemcorwin** [comment]
@brockfanning Thanks for the interest! This particular issue is just to explore potentially renaming the repo, so nothing to do here for now.

**Comment by davemcorwin** [comment]
I don't see this happening any time soon, closing for now.
