### ISSUE TITLE
Build failure on Gatsby 2.8.5

### ISSUE THREAD

**Issue by melpers** [18F/federalist-uswds-gatsby#19]
#### User Story

A Federalist user using the uswds gatsby template should be able run node gatsby package > 2.8.5

#### Background (Optional)

<TODO>

#### Acceptance Criteria

- [x] template builds successfully with node gatsby package >= 2.8.5
- [x] Change made live via deploy of gatsby template

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

- [ ] <TODO>

After updating Gatsby to 2.8.5 & React to 16.8.6 it was failing to build (but would run develop) with the error:

`- Your site's gatsby-node.js is exporting a variable named "onClientEntry" which isn't an API.`

Seems that is now a Browser API, and should be moved out of `gatsby-node.js` and into `gatsby-browser.js`.

**Comment by melpers** [comment]
I was able to address this by adding `import "uswds_polyfills"` into `gatsby-browser.js` and removing the `onClientEntry` code from `gatsby-node.js`, however the old version had a `try ... catch` around it so there may be a better way to handle this change.

**Comment by amirbey** [comment]
resolved in #21
