### ISSUE TITLE
Implement documentation page navigation

### ISSUE THREAD

**Issue by davemcorwin** [18F/federalist-uswds-gatsby#24]
@davemcorwin commented on [Thu Jan 30 2020](https://github.com/18F/federalist-uswds-gatsby2/issues/6)

Currently the navigation on the documentation pages is static and points to nowhere. Actually implement this navigation to make it easier for users to use. Also applies to the Jekyll template.

**Comment by epicfaace** [comment]
We implemented this navigation in our own repository (along with highlighting navs as "active" or not based on what page they're currently on), and allowed the user to specify `sidenav: [sitenav name]`, if it helps to go off of:

https://github.com/cisagov/crossfeed/blob/a9be38a4a8a54cf1722870f208fdd95ecf2d37ea/docs/src/components/sidenav.js#L51

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.
