### ISSUE TITLE
Add optional subagency configuration to DAP script src

### ISSUE THREAD

**Issue by davemcorwin** [18F/federalist-uswds-gatsby#33]
#### User Story

A user should be able to specify a subagency when using the jekyll starter

#### Background (Optional)

https://github.com/18F/federalist-uswds-jekyll/pull/59

#### Acceptance Criteria

- [x] able to specify subagency and data is capture by DAP
- [x] Change made live via deploy of template gatsby

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

- [x] add subagency confiuration ... see https://github.com/18F/federalist-uswds-jekyll/pull/59 as example

**Comment by amirbey** [comment]
implemented by @davemcorwin
