### ISSUE TITLE
Community Enhancements

### ISSUE THREAD

**Issue by its-aye-lisa** [18F/federalist-uswds-gatsby#367]
I've been learning to do web development and using Gatsby as a start. I've been setting up a personal site by using a Gatsby Starter and didn't see this template on the Starter Library -- is that something that has been considered? 

One of the features that exist for the starter sites is that they all have a demo site to go with the template, and it is listed in the GitHub repo. I didn't see that with this template and thought it would be a great feature.

**Comment by davemcorwin** [comment]
Thanks @its-a-lisa ! responses below

> I've been learning to do web development and using Gatsby as a start. I've been setting up a personal site by using a Gatsby Starter and didn't see this template on the Starter Library -- is that something that has been considered?

No, we haven't considered this. This starter is specific to Federalist and I don't think we are looking to drive traffic from the Gatsby site or the community at large. I'm open to hearing why we may want to do this and if it's worth the effort given our constraints.

> One of the features that exist for the starter sites is that they all have a demo site to go with the template, and it is listed in the GitHub repo. I didn't see that with this template and thought it would be a great feature.

There is currently a [preview deployment available](https://federalist-b146cf1e-c756-4b1f-bb83-c516cac94fbb.app.cloud.gov/site/18f/federalist-uswds-gatsby/). Perhaps we should add this link to the Readme? It's also accessible from our [marketing site](https://federalist.18f.gov/documentation/templates/).
