### ISSUE TITLE
Gatsby 3

### ISSUE THREAD

**Issue by fpigeonjr** [18F/federalist-uswds-gatsby#449]
Will there be a Gatsby 3 example/template?

Love this project and have used it as a template for multiple work projects with the government.

Here is the Gatsby migration path in case you are interested. 

https://www.gatsbyjs.com/docs/reference/release-notes/migrating-from-v2-to-v3/

[Gatsby 3 was released in March 2021](https://www.gatsbyjs.com/docs/reference/release-notes/v3.0/).

**Comment by davemcorwin** [comment]
Yes, not sure when, but this will be updated to v3

**Comment by fpigeonjr** [comment]
That's great news @davemcorwin. Looking forward to seeing the new implementation.

**Comment by davemcorwin** [comment]
Thanks to @hursey013 this was just updated to Gatsby v4!

**Comment by fpigeonjr** [comment]
Thanks @hursey013!
