### ISSUE TITLE
Add support for XML sitemaps

### ISSUE THREAD

**Issue by dawnpm** [18F/federalist-uswds-gatsby#466]
As a website maintainer, I want my website to publish an XML format sitemap using a plugin or similar, so I can get better search coverage and also not have to mess with creating or updating the sitemap manually.

https://www.gatsbyjs.com/plugins/gatsby-plugin-sitemap/

The plugin documentation recommends to put the sitemap itself in a non-standard location. If possible, please put it at the root.

**Comment by hursey013** [comment]
Hi @dawnpm - I know a sitemap plugin was [recently added](https://github.com/18F/federalist-uswds-gatsby/pull/475), does that address this issue? If there are any additional follow ups, would you mind opening a new issue? I know @amanifarooque mentioned there might be some additional work w/ the sitemap. Thanks!
