### ISSUE TITLE
Future of the project

### ISSUE THREAD

**Issue by cschroedl-gov** [18F/federalist-uswds-gatsby#473]
Hello @davemcorwin ! I found this project while searching for USWDS-compatible static site generation tools. I noticed that this project relies on v2 of Gatsby, [which is no longer supported as of January 1st, 2022](https://www.gatsbyjs.com/docs/reference/release-notes/gatsby-version-support/#release-and-support-schedule). Do you or the other maintainers have funding + time to update this to a supported version of Gatsby in the next couple of months?

**Comment by davemcorwin** [comment]
Thanks to @hursey013 this was just updated to Gatsby v4!

**Comment by cschroedl-gov** [comment]
👏 Thank You!
