### ISSUE TITLE
Integrate data from an api

### ISSUE THREAD

**Issue by davemcorwin** [18F/federalist-uswds-gatsby#7]
Demonstrate Gatsby pulling data from external cloud.gov hosted APIs

**Comment by davemcorwin** [comment]
@eddietejeda Did you have anything specific in mind for this or will any dummy API suffice?

**Comment by eddietejeda** [comment]
Any API will do.

**Comment by davemcorwin** [comment]
👍

**Comment by davemcorwin** [comment]
Do we have a cloud.gov org under which I should put this application?
